# Generated by Django 5.1.1 on 2024-11-19 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortalCMAS', '0003_membresias_rename_actividad_clases_actividad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clases',
            old_name='actividad',
            new_name='Actividad',
        ),
        migrations.RenameField(
            model_name='clases',
            old_name='horario',
            new_name='Horario',
        ),
        migrations.RenameField(
            model_name='clases',
            old_name='maquinas_disponibles',
            new_name='Maquinas_Diponibles',
        ),
    ]
